# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "People"
  url = "#people"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 40

[[main]]
  name = "Courses"
  url = "courses/"
  weight = 50

[[main]]
  name = "Blog"
  url = "blog/"
  weight = 60
  
[[main]]
  name = "Join us!"
  url = "prospective/"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70


