---
title:  " "
---

<br />

I welcome applications from students interested in joining the Department of Environment and Society as Masters or Ph.D. students.  Students with interests in:

* Agricultural adaptation to climate change,
* Geospatial data science,
* Agroecology,
* Water and food security or
* Landscape ecology

can contact me at [emily.burchfield@usu.edu](mailto:emily.burchfield@usu.edu). Please include a brief description of your research interests, your CV, unofficial transcripts, and GRE scores.  Prior experience in GIS, programming, and statistics is strongly recommended.  Prospective students can find more information about the application process on the [Department of Environment and Society website.](http://qcnr.usu.edu/envs/graduate/future_students)

Funds are available for a limited number of competitive research assistant positions.  Students are also encouraged to consider [Utah State University fellowships](http://rgs.usu.edu/graduateschool/tuition-financial-aid/) and the [Climate Adaptation Fellows program](https://climateadaptation.usu.edu/admission/program-description/).  I am also happy to help motivated students apply for other funding opportunities.

***
#### **Current BURCH-lab members:** 

* [Cody Edwards](https://qcnr.usu.edu/envs/people/graduates/edwards_cody), M.S. in Ecology
* [Stan Rhodes](https://qcnr.usu.edu/envs/people/graduates/rhodes_stan), Ph.D student in Environment and Society
* Britta Schumacher, M.S. in Ecology
* [Kaitlyn Spangler](https://qcnr.usu.edu/envs/people/graduates/spangler_kaitlyn), Ph.D. student in Environment and Society


