---
title:  "  "
---

<br />

 
## Current Projects

#### Agricultural diversity and yield

* *Funded by a [USU RGS Research Catalyst Grant](http://rgs.usu.edu/rd/rc/)*
* National study of the relationship between landscape composition and agricultural production. 

#### Agricultural resilience to climate stress

* *Funded by the [Utah Agricultrual Experiment Station](https://uaes.usu.edu/)*
* Identification of the shared characteristics of agricultural systems showing resilience to extreme heat and water stress over the last 30 years in the continental United States.  

#### Predicting and preparing for future cropscapes

* Generation of spatially explicit projections of yield and cultivated extent for major crops in the United States.
* Identify and support regions of major agricultural transition.

#### Drivers of farmer decision-making

* Qualitative interviews assessing the multiscalar factors that affect cultivation decisions and conservation behavior at the farm- and landscape scale.

***

## Published Research 

* **Burchfield, E.**, Matthews-Pennanen, N., Schoof, J., Lant, C. (2019). Changing yields in the central U.S. under climate and technological change. *Climatic Change*, *In press*. Pre-print available [here](files/Burchfield_FY_preprint.pdf).
* **Burchfield, E.**, Nelson, K. Spangler, K. (2019). The impact of agricultural diversification on U.S. crop production. *Agriculture, Ecosystems & Environment.* 285:106615. [https://doi.org/10.1016/j.agee.2019.106615](https://doi.org/10.1016/j.agee.2019.106615). Pre-print available [here](files/Burchfield_SDI_preprint.pdf).
* Tozier de la Poterie, A., **Burchfield, E.**, Carrico, A. (2018). The implications
 of group norms for adaptation in collectively-managed agricultural
 systems: evidence from Sri Lankan Paddy farmers.  *Ecology and Society*, *23*(3):21. [https://doi.org/10.5751/ES-10175-230321](https://doi.org/10.5751/ES-10175-230321)
* **Burchfield, E.**, Williams, N., Carrico, A. (2018). [Rescaling drought mitigation in rural Sri Lanka.](https://link.springer.com/article/10.1007/s10113-018-1374-y), *Regional Environmental Change*, 1-9.  
* **Burchfield, E.**, Tozier de la Poterie, A. (2018).  [Determinants of crop diversifictaion in rice-dominated Sri Lankan agricultural systems.](https://www.sciencedirect.com/science/article/pii/S0743016717311671)  *Journal of Rural Studies*, *61*, 206-215.
* Nay, J., **Burchfield, E.**, Gilligan, J. (2018).  [A machine learning approach to forecasting remotely sensed vegetation health.](https://www.tandfonline.com/doi/pdf/10.1080/01431161.2017.1410296?needAccess=true)  *International Journal of Remote Sensing*,  *39*(6), 1800 - 1816.  Check out the project website [here.](http://johnjnay.com/forecastVeg/)
* Nelson, K., **Burchfield, E.** (2017).  [Effects of the Structure of Water Rights on Agricultural Production During Drought: A Spatio-temporal Analysis of California's Central Valley.](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1002/2017WR020666)  *Water Resources Research*, *53*(10), 8293 - 8309. 
* **Burchfield, E.**, Gilligan, J. (2016). [Agricultural adaptation to drought in the Sri Lankan dry zone.](https://www.sciencedirect.com/science/article/pii/S0143622816306063) *Applied Geography*, *77*, 92-100.
* **Burchfield, E.**, Gilligan, J. (2016).  [Dynamics of individual and collective agricultural adaptation to water scarcity.](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2807452)  *Winter Simulation Conference 2016 Proceedings.*
* **Burchfield, E.**, Nay, J., Gilligan, J. (2016).  [Application of machine learning to prediction of vegetation health.](https://www.int-arch-photogramm-remote-sens-spatial-inf-sci.net/XLI-B2/465/2016/isprs-archives-XLI-B2-465-2016.pdf)  *The International Archives of the Photogrammetry, Remote Sensing and Spatial Information Sciences.*  XLI-B2, 465-469, doi:10.5194/isprs-archives-XLI-B2-465-2016.
* Gunda, T., Benneyworth, L., **Burchfield, E.** (2015).  [Exploring water indices and associated parameters: A case study approach](http://web.b.ebscohost.com/abstract?direct=true&profile=ehost&scope=site&authtype=crawler&jrnl=13667017&AN=100841573&h=KAR6SkiZ6aGgJxGIn0te5H3G7yE9tPmpddCL5wLWUYiKEYtijePz4RumHNNwI%2bkj%2bc9IxBQO0ytLM5lJensL3A%3d%3d&crl=f&resultNs=AdminWebAuth&resultLocal=ErrCrlNotAuth&crlhashurl=login.aspx%3fdirect%3dtrue%26profile%3dehost%26scope%3dsite%26authtype%3dcrawler%26jrnl%3d13667017%26AN%3d100841573), *Water Policy*, *17*(1), 98 - 111.

